language: node_js
node_js: "4.3"

on:
   tags: true

sudo: true

install:
  - npm install

env:
  - CONTENTFUL_CONTENT_DELIVERY_API_KEY=0abcd CONTENTFUL_CONTENT_PREVIEW_API_KEY=0abcd CONTENTFUL_SPACE_ID=0abcd API_SEARCH_URL_TIER_1=http://localhost:8000/1 API_SEARCH_URL_TIER_2=http://localhost:8000/1

script:
  - npm run lint
  - npm run regression

after_success:
  - sudo pip install --upgrade pip
  - sudo pip install awscli
  - aws configure set AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
  - aws configure set AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
  - chmod +x ./deploy/deploy.sh
  - ./deploy/deploy.sh
