language: node_js
node_js: "4.3"

on:
   tags: true

sudo: true

install:
  - npm install
  - npm install jscs jshint -g

env:
  - CONTENTFUL_CONTENT_DELIVERY_API_KEY=0abcd
  - CONTENTFUL_CONTENT_PREVIEW_API_KEY=0abcd
  - CONTENTFUL_SPACE_ID=0abcd

script:
  - jscs . && jshint .
  - npm run regression

after_success:
  - sudo pip install --upgrade pip
  - sudo pip install awscli
  - aws configure set AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
  - aws configure set AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
  - chmod +x ./deploy/deploy.sh
  - ./deploy/deploy.sh
