language: node_js
node_js: "4.3"

on:
   tags: true

sudo: true

install:
  - npm install

env:
  global:
    - CONTENTFUL_CONTENT_DELIVERY_API_KEY=0abcd
    - CONTENTFUL_CONTENT_PREVIEW_API_KEY=0abcd
    - CONTENTFUL_SPACE_ID=0abcd
    - API_SEARCH_URL_TIER_1=http://localhost:8000/1
    - API_SEARCH_URL_TIER_2=http://localhost:8000/1
    - GOOGLE_API_CLIENT_EMAIL=client-email-goes-in-here
    - GOOGLE_API_PRIVATE_KEY='-----BEGIN PRIVATE KEY-----\nabcd8=\n-----END PRIVATE KEY-----\n'
    - VN_ANALYTICS_ID=ga:1234
    - PH_ANALYTICS_ID=ga:1234
    - ID_ANALYTICS_ID=ga:1234
    - MM_ANALYTICS_ID=ga:1234
    - MX_ANALYTICS_ID=ga:1234
    - BD_ANALYTICS_ID=ga:1234
    - PK_ANALYTICS_ID=ga:1234
    - LK_ANALYTICS_ID=ga:1234
    - SA_ANALYTICS_ID=ga:1234
    - QA_ANALYTICS_ID=ga:1234

script:
  - npm run lint
  - npm run regression

after_success:
  - sudo pip install --upgrade pip
  - sudo pip install awscli
  - aws configure set AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
  - aws configure set AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
  - chmod +x ./deploy/deploy.sh
  - ./deploy/deploy.sh
