web_service:
  image: contentservice:latest
  container_name: contentservice

  ports:
    - 8082:8082

  env_file:
    - ./app.env

  volumes:
    - .:/src
    - ./docker_logs/contentservice:/var/log/applications/contentservice
