swagger: '2.0'
info:
  title: Content Service API
  description: Contenful content platform consolidated with search engine results 
  version: "0.1.0"
host: 2hps15f6m1.execute-api.ap-southeast-1.amazonaws.com
schemes:
  - https
basePath: /staging/content
produces:
  - application/hal+json
  - application/json
paths:
  /{postType}/{postSlug}:
    get:
      summary: get one Post by type and slug
      description: General knowledge and advice about cars
      parameters:
        - name: postType
          in: path
          description: type of post
          required: true
          type: string
          enum: ['advice','finance','insurance']
        - name: postSlug
          in: path
          description: post unique text identifier
          required: true
          type: string
          pattern: ^[a-z0-9]+
      tags:
        - Posts
        - Advices
      responses:
        200:
          description: one Post content
          schema:
            type: object
            items:
              $ref: '#/definitions/AdviceResponse'
        400:
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Not Found Error
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
        424:
          description: Failed Dependency Error
          schema:
            $ref: '#/definitions/Error'
      x-amazon-apigateway-integration:
          responses:
            default:
              statusCode: '200'
          uri: 'arn:aws:apigateway:ap-southeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-southeast-1:993784152963:function:getPost/invocations'
          passthroughBehavior: 'when_no_match'
          httpMethod: 'POST'
          contentHandling: 'CONVERT_TO_TEXT'
          type: 'aws'
definitions:
  AdviceResponse:
    type: object
    properties:
      advice:
        type: object
        description: Advice data object
        items:
          $ref: '#/definitions/Post'
      products:
        type: array
        description: Recommended products associated with post
        items:
          $ref: '#/definitions/Listing'
  Post:
    type: object
    properties:
      slug:
        type: string
        description: Unique slug identifier
      title:
        type: string
        description: post title
      metadescription:
        type: string
        description: post meta description
      hrefLang:
        type: array
        items:
          type: string
        description: post list of langs
      canonicalTag:
        type: string
        description: post canonical tag
      postImage:
        type: object
        items:
          $ref: '#/definitions/Image'
      category:
        type: array
        items:
          type: string
        description: post list of categories
      content:
        type: string
        description: post content
      crossLinking:
        type: array
        items:
          $ref: '#/definitions/Widget'
        description: Relevant crosslinks for post
      suggestionsWidget:
        type: array
        items:
          $ref: '#/definitions/Widget'
        description: Relevant suggestion widgets for post
      tags:
        type: string
        description: Post tags
      author:
        type: object
        items:
          $ref: '#/definitions/Author'
      language:
        type: array
        items:
          type: string
        description: Post language
      country:
        type: array
        items:
          type: string
        description: Applicable country for post
      robotsMetatags:
        type: array
        items:
          type: string
        description: Robots meta tags
  Widget:
    type: object
    properties:
      widgetName:
        type: string
        description: post widget name
      priceFrom:
        type: integer
        description: price from
      priceTo:
        type: integer
        description: price to
      yearFrom:
        type: integer
        description: year from
      yearTo:
        type: integer
        description: year to
      mileageFrom:
        type: integer
        description: mileage from
      mileageTo:
        type: integer
        description: mileage to
      transmission:
        type: array
        items:
          type: string
        description: transmission options
      sellerType:
        type: array
        items:
          type: string
        description: seller type options
      category:
        type: array
        items:
          type: string
        description: vehicle category options
      condition:
        type: array
        items:
          type: string
        description: vehicle condition options
      fuel:
        type: array
        items:
          type: string
        description: fuel options
      model:
        type: array
        items:
          type: string
        description: model options
      brand:
        type: array
        items:
          type: string
        description: brand options
  Image:
    type: object
    properties:
      title:
        type: string
        description: post image title
      description:
        type: string
        description: post image description
      file:
        type: object
        properties:
          url:
            type: string
            description: image url
          details:
            type: object
            properties:
              size:
                type: integer
                description: image size
              image:
                type: object
                properties:
                  width:
                    type: integer
                    description: image width
                  height:
                    type: integer
                    description: image height
                description: image dimensions
          fileName:
            type: string
            description: image file name
          contentType:
            type: string
            description: image content type
  Author:
    type: object
    properties:
      fullName:
        type: string
        description: author's full name
      description:
        type: string
        description: author's description
  Listing:
    type: object
    properties:
      sku:
        type: string
        description: listing sku
      slug:
        type: string
        description: listing slug
      title:
        type: string
        description: listing title
      vertical:
        type: string
        description: listing vertical name
      brand:
        type: string
        description: listing brand name
      model:
        type: string
        description: listing model name
      vertical_id:
        type: string
        description: listing vertical unique id
      brand_id:
        type: string
        description: listing brand unique id
      model_id:
        type: string
        description: listing model unique id
      categories:
        type: array
        items:
          type: object
          properties:
            category_id:
              type: string
              description: category unique id
            category_name:
              type: string
              description: category name
      listingImage:
        type: object
        items:
          $ref: '#/definitions/Image'
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
